# Advanced NumPy usage

In [1]:
from random import randint

gold = [randint(0, 100) for i in range(10000000)]

In [2]:
%%timeit
silver = []
for gold_value in gold:
    silver.append(12 * gold_value)

876 ms ± 1.93 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [3]:
%timeit silver = [12 * gold_value for gold_value in gold]

410 ms ± 2.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [1]:
import numpy as np
gold = np.random.randint(0, 100, (10000000,))

In [2]:
%%timeit
silver = np.empty(gold.shape)
for i in range(gold.shape[0]):
    silver[i] = 12 * gold[i]

2.82 s ± 168 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [3]:
%timeit silver = 12 * gold

31.8 ms ± 4.41 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [2]:
loots = np.random.randint(0, 100, (10,))
shares = np.array([.7, 1., 1.3, 2., 1.])
loots * shares

ValueError: operands could not be broadcast together with shapes (10,) (5,) 

In [2]:
gold = np.random.randint(0, 100, (10,))
gold

array([ 7, 74, 65, 88,  9, 26, 53, 62, 12, 68])

In [3]:
ratio = np.array(12)
ratio_wide = ratio * np.ones(gold.shape)
ratio_wide

array([12., 12., 12., 12., 12., 12., 12., 12., 12., 12.])

In [4]:
gold * ratio_wide

array([  84.,  888.,  780., 1056.,  108.,  312.,  636.,  744.,  144.,
        816.])

In [3]:
loots

array([59,  5, 41, 54, 38, 28, 55, 42, 69, 97])

In [4]:
loots.shape

(10,)

In [5]:
loots[:, np.newaxis]

array([[59],
       [ 5],
       [41],
       [54],
       [38],
       [28],
       [55],
       [42],
       [69],
       [97]])

In [6]:
loots[:, np.newaxis].shape

(10, 1)

In [7]:
loots[:, None]

array([[59],
       [ 5],
       [41],
       [54],
       [38],
       [28],
       [55],
       [42],
       [69],
       [97]])

In [12]:
np.newaxis is None

True

In [5]:
loots = np.random.randint(0, 100, (10,))
shares = np.array([.7, 1., 1.3, 2., 1.])
loots[:, np.newaxis] * shares

array([[ 10.5,  15. ,  19.5,  30. ,  15. ],
       [ 28.7,  41. ,  53.3,  82. ,  41. ],
       [ 56.7,  81. , 105.3, 162. ,  81. ],
       [ 46.9,  67. ,  87.1, 134. ,  67. ],
       [ 28.7,  41. ,  53.3,  82. ,  41. ],
       [ 53.2,  76. ,  98.8, 152. ,  76. ],
       [ 18.9,  27. ,  35.1,  54. ,  27. ],
       [ 22.4,  32. ,  41.6,  64. ,  32. ],
       [  2.8,   4. ,   5.2,   8. ,   4. ],
       [ 49.7,  71. ,  92.3, 142. ,  71. ]])

In [4]:
names = np.array(['bard', 'mage', 'leader', 'paladin', 'ranger'])
# character attributes = health, speed, strength, mana
attributes = np.array([[72, 15, 48, 22],
                      [68, 8, 44, 87],
                      [65, 12, 56, 28],
                      [82, 7, 78, 0],
                      [67, 11, 62, 14]])
attributes

array([[72, 15, 48, 22],
       [68,  8, 44, 87],
       [65, 12, 56, 28],
       [82,  7, 78,  0],
       [67, 11, 62, 14]])

In [3]:
sorter = attributes[:, 0].argsort()
sorter

array([2, 4, 1, 0, 3])

In [4]:
attributes[sorter]

array([[65, 12, 56, 28],
       [67, 11, 62, 14],
       [68,  8, 44, 87],
       [72, 15, 48, 22],
       [82,  7, 78,  0]])

In [5]:
names[sorter]

array(['leader', 'ranger', 'mage', 'bard', 'paladin'], dtype='<U7')

In [11]:
contributions = np.array([.7, 1., 1.3, 2., 1.])
attributes.T * contributions

array([[ 50.4,  68. ,  84.5, 164. ,  67. ],
       [ 10.5,   8. ,  15.6,  14. ,  11. ],
       [ 33.6,  44. ,  72.8, 156. ,  62. ],
       [ 15.4,  87. ,  36.4,   0. ,  14. ]])

In [8]:
loots = np.random.randint(-100, 100, (10,))
loots

array([-97,   5,   8, -59,  -3, -40,  30,  58,  -3,  -9])

In [9]:
loots > 0

array([False,  True,  True, False, False, False,  True,  True, False,
       False])

In [10]:
loots[loots > 0]

array([ 5,  8, 30, 58])

In [12]:
loots[np.logical_and(loots >= 5, loots <= 30)]

array([ 5,  8, 30])

In [2]:
dungeon_difficulties = np.array([[  7,   7,   5,   1,   5,   6,   9,   6,  10,   4,   2,   3],
                                 [ 10,  16,  12,  12,  18,   0,  16,  20,  12,   4,  12,  12],
                                 [  3,   3,  12,  15,   6,  12,  27,   6,   3,  30,  15,  27],
                                 [ 24,  12,  40,  32,  40,  12,  12,  16,  24,   4,  16,   4],
                                 [ 25,   0,  35,   0,  40,  50,  40,  20,  35,  25,  25,  35],
                                 [ 30,  24,  36,  48,  42,   6,  18,  54,  36,  54,  12,  24],
                                 [ 49,  28,  42,  70,  21,  42,   7,  42,  49,  42,   0,  63],
                                 [  8,  16,  72,  16,  24,  40,  40,  40,  64,  24,  24,   8],
                                 [ 81,  62,  18,  81,  81,  27,  27,  45,  18,  27,  90,  36],
                                 [ 80,  90,  20, 100,  80,  90,  50,  80,  70,  90,  60,  40]])

In [3]:
dungeon_difficulties[[1, 4, 7], [0, 2, 3]]

array([10, 35, 16])

In [4]:
dungeon_difficulties[np.ix_([1, 4, 7], [0, 2, 3])]

array([[10, 12, 12],
       [25, 35,  0],
       [ 8, 72, 16]])

In [7]:
np.ones(dungeon_difficulties.shape).astype(int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [1]:
import numpy as np

In [2]:
objects_in_dungeons = np.array([[1, 1, 1, 2, 1, 3, 1, 5, 7, 1, 1, 9],
                                [1, 1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 10],
                                [1, 1, 1, 5, 1, 1, 3, 1, 2, 1, 1, 8],
                                [1, 1, 1, 1, 10, 1, 1, 2, 2, 2, 1, 13],
                                [1, 1, 1, 2, 3, 3, 5, 8, 1, 2, 4, 10],
                                [2, 3, 2, 2, 1, 5, 6, 1, 9, 2, 7, 6],
                                [2, 2, 2, 1, 8, 2, 2, 1, 6, 1, 5, 12],
                                [3, 2, 3, 5, 1, 1, 4, 2, 1, 7, 1, 9],
                                [3, 3, 2, 2, 4, 3, 6, 2, 8, 1, 1, 17],
                                [2, 2, 2, 3, 3, 1, 8, 1, 1, 1, 1, 18]])

In [3]:
np.isin(objects_in_dungeons, 8).nonzero()

(array([2, 4, 6, 8, 9]), array([11,  7,  4,  8,  6]))

In [4]:
objects_in_dungeons[np.isin(objects_in_dungeons, np.arange(10, 20))]

array([10, 10, 13, 10, 12, 17, 18])

In [5]:
dungeon_list = np.array([1, 4, 7])
floor_list = np.array([0, 2, 3])
np.isin(dungeon_difficulties, dungeon_list)

(array([0, 0, 0, 0, 1, 3, 3, 6]), array([ 0,  1,  3,  9,  9,  9, 11,  6]))

In [44]:
%timeit dungeon_difficulties == 81

803 ns ± 10.1 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [45]:
%timeit np.isin(dungeon_difficulties, np.array([81]))

10 µs ± 25.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
dungeon_difficulties[dungeon_difficulties]

In [37]:
N = 10000
large_dungeons = (np.arange(10, 110, N)[:, None] * np.round(np.random.rand(N, 12), decimals=1)).astype(int)

In [1]:
import numpy as np

In [2]:
loots_per_character_per_floor = np.random.randint(0, 100, (10, 5, 12))
loots_per_character_per_floor[0]

array([[43, 79, 43, 60, 59, 71, 22, 62, 88, 90, 60, 32],
       [30, 80, 81, 40, 31, 23,  3, 10, 99, 58, 99, 49],
       [ 5, 52, 28, 12, 32,  2, 94, 48,  4, 50, 76,  3],
       [14, 31, 38, 56, 68,  0, 12, 23,  7, 99, 66, 48],
       [53, 79,  6, 76, 65, 37, 28,  8, 74, 46, 66, 95]])

In [3]:
loots_per_character_per_floor[:, :, -1]

array([[32, 49,  3, 48, 95],
       [82, 87, 14, 73, 31],
       [56, 64, 62, 43, 59],
       [87, 61, 86, 42, 58],
       [36, 68,  4, 39, 76],
       [98, 22, 14, 93,  4],
       [23, 83, 29, 51, 56],
       [21,  1, 51, 27, 73],
       [ 8, 63,  9, 62, 74],
       [13, 89, 25, 15, 91]])

In [4]:
loots_per_character_per_floor[..., -1]

array([[32, 49,  3, 48, 95],
       [82, 87, 14, 73, 31],
       [56, 64, 62, 43, 59],
       [87, 61, 86, 42, 58],
       [36, 68,  4, 39, 76],
       [98, 22, 14, 93,  4],
       [23, 83, 29, 51, 56],
       [21,  1, 51, 27, 73],
       [ 8, 63,  9, 62, 74],
       [13, 89, 25, 15, 91]])

# Indexing

In [1]:
import numpy as np
np.set_printoptions(suppress=True)

In [2]:
devises = np.array([20, 1.8, .5, 12])
loots = np.concatenate([np.random.randint(0, 4, (10,))[:, None],
                        np.random.randint(0, 100, (10,))[:, None]],
                       axis=1)
loots

array([[ 1, 28],
       [ 3, 58],
       [ 1, 70],
       [ 2, 31],
       [ 1, 54],
       [ 3, 34],
       [ 3,  9],
       [ 1, 34],
       [ 3, 58],
       [ 0, 14]])

In [3]:
loots[:, 1][:, None] * devises

array([[ 560. ,   50.4,   14. ,  336. ],
       [1160. ,  104.4,   29. ,  696. ],
       [1400. ,  126. ,   35. ,  840. ],
       [ 620. ,   55.8,   15.5,  372. ],
       [1080. ,   97.2,   27. ,  648. ],
       [ 680. ,   61.2,   17. ,  408. ],
       [ 180. ,   16.2,    4.5,  108. ],
       [ 680. ,   61.2,   17. ,  408. ],
       [1160. ,  104.4,   29. ,  696. ],
       [ 280. ,   25.2,    7. ,  168. ]])

In [4]:
(loots[:, 1][:, None] * devises)[np.arange(len(loots)), loots[:, 0]]

array([ 50.4, 696. , 126. ,  15.5,  97.2, 408. , 108. ,  61.2, 696. ,
       280. ])

# C-order vs F-order

In [2]:
a = np.random.rand(100, 1000000)
%timeit  a.sum(axis=0)

144 ms ± 1.48 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [3]:
b = a.astype(dtype=a.dtype, order='F')
%timeit  b.sum(axis=0)

60.8 ms ± 70.7 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


# Einsum

In [2]:
# character attributes = health, speed, strength, mana
attributes = np.array([[72, 15, 48, 22],
                      [68, 8, 44, 87],
                      [65, 12, 56, 28],
                      [82, 7, 78, 1],
                      [67, 11, 62, 14]])
attributes.shape

(5, 4)

In [3]:
loots = np.random.randint(0, 100, (3, 5))
loots

array([[ 7, 46,  7,  6, 37],
       [66, 48, 19, 57, 86],
       [21, 94, 35, 61, 12]])

In [4]:
loots[:, :, None] / attributes

array([[[ 0.09722222,  0.46666667,  0.14583333,  0.31818182],
        [ 0.67647059,  5.75      ,  1.04545455,  0.52873563],
        [ 0.10769231,  0.58333333,  0.125     ,  0.25      ],
        [ 0.07317073,  0.85714286,  0.07692308,  6.        ],
        [ 0.55223881,  3.36363636,  0.59677419,  2.64285714]],

       [[ 0.91666667,  4.4       ,  1.375     ,  3.        ],
        [ 0.70588235,  6.        ,  1.09090909,  0.55172414],
        [ 0.29230769,  1.58333333,  0.33928571,  0.67857143],
        [ 0.69512195,  8.14285714,  0.73076923, 57.        ],
        [ 1.28358209,  7.81818182,  1.38709677,  6.14285714]],

       [[ 0.29166667,  1.4       ,  0.4375    ,  0.95454545],
        [ 1.38235294, 11.75      ,  2.13636364,  1.08045977],
        [ 0.53846154,  2.91666667,  0.625     ,  1.25      ],
        [ 0.74390244,  8.71428571,  0.78205128, 61.        ],
        [ 0.17910448,  1.09090909,  0.19354839,  0.85714286]]])

In [5]:
np.einsum('ij, jk -> ijk', loots, 1 / attributes)

array([[[ 0.09722222,  0.46666667,  0.14583333,  0.31818182],
        [ 0.67647059,  5.75      ,  1.04545455,  0.52873563],
        [ 0.10769231,  0.58333333,  0.125     ,  0.25      ],
        [ 0.07317073,  0.85714286,  0.07692308,  6.        ],
        [ 0.55223881,  3.36363636,  0.59677419,  2.64285714]],

       [[ 0.91666667,  4.4       ,  1.375     ,  3.        ],
        [ 0.70588235,  6.        ,  1.09090909,  0.55172414],
        [ 0.29230769,  1.58333333,  0.33928571,  0.67857143],
        [ 0.69512195,  8.14285714,  0.73076923, 57.        ],
        [ 1.28358209,  7.81818182,  1.38709677,  6.14285714]],

       [[ 0.29166667,  1.4       ,  0.4375    ,  0.95454545],
        [ 1.38235294, 11.75      ,  2.13636364,  1.08045977],
        [ 0.53846154,  2.91666667,  0.625     ,  1.25      ],
        [ 0.74390244,  8.71428571,  0.78205128, 61.        ],
        [ 0.17910448,  1.09090909,  0.19354839,  0.85714286]]])

# View vs copy

In [11]:
a = np.arange(18).reshape(3, 6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [10]:
a[np.arange(3), [1, 2, 3]] = -1
a

array([[ 0, -1,  2,  3,  4,  5],
       [ 6,  7, -1,  9, 10, 11],
       [12, 13, 14, -1, 16, 17]])

In [16]:
a[np.mod(a, 3) == 0] = -1
a

array([[-1,  1,  2, -1,  4,  5],
       [-1,  7,  8, -1, 10, 11],
       [-1, 13, 14, -1, 16, 17]])

In [41]:
np.arange(len(loots)), loots[:, 0]

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([3, 4, 2, 3, 2, 2, 4, 3, 0, 4]))

In [1]:
import numpy as np

In [36]:
a = np.arange(27).reshape((9, 3))
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (9,) (2,) 

## Under the hood

In [ ]:
vectorization -> splitting loot part depending on character weight / contribution


## Vectorization

The maze of indexing

In [ ]:
normalization in one line

## Broadcasting

In [ ]:
Crazy things with indexing

In [ ]:
using weights / weighting samples

## Ufuncs

In [1]:
import numpy as np

In [2]:
# closest value from a reference list
ref_list = np.array([2, 5, 12])

In [3]:
def closest(a, ref):
    return ref[(np.abs(ref - a)).argmin()]    

In [4]:
x = np.random.randint(0, 20, size=(1000))

In [5]:
%timeit np.apply_along_axis(closest, 1, x[:, None], ref_list)

5.81 ms ± 554 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [6]:
closest_vect = np.vectorize(closest, excluded=['ref'])

In [7]:
%timeit closest_vect(x, ref=ref_list)

4.29 ms ± 516 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [8]:
def closest_numpy(arr, ref):
    return ref[(np.abs(arr[:, None] - ref)).argmin(axis=1)]

In [9]:
ex = np.arange(5)
np.abs(ex[:, None] - ref_list)

array([[ 2,  5, 12],
       [ 1,  4, 11],
       [ 0,  3, 10],
       [ 1,  2,  9],
       [ 2,  1,  8]])

In [10]:
%timeit closest_numpy(x, ref=ref_list)

28.7 µs ± 1.9 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [11]:
from numba import vectorize, int64

In [12]:
@vectorize([int64(int64)], nopython=True)
def closest_numba(a):
    ref = ref_list
    return ref[(np.abs(ref - a)).argmin()]    

In [13]:
%timeit closest_numba(x)

96.8 µs ± 3.36 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [14]:
ex = np.arange(15)
closest_numba.at(ex, ex < 10)
ex

array([ 2,  2,  2,  2,  5,  5,  5,  5,  5, 12, 10, 11, 12, 13, 14])

In [15]:
np.add.reduce(ex)

105

In [16]:
ex.sum()

105

## Numba and Numexpr

In [1]:
import numpy as np
np.set_printoptions(suppress=True)

$ d_{euclid}(a, b) = \sqrt{||a-b||^2} =  \sqrt{ (a_1 - b_1)^2 + (a_2 - b_2)^2}  $

In [2]:
N = 1000
A = np.random.rand(N, 2) + 1
B = np.random.rand(N, 2) + 1

In [3]:
def euclid(a, b):
    return np.sqrt(np.dot(a - b, (a - b).T))

In [4]:
def naive_euclid(X, Y):
    res = np.empty((len(X), len(Y)))
    for i in range(len(X)):
        for j in range(len(Y)):
            res[i, j] = euclid(X[i], Y[j])
    return res

In [5]:
%timeit naive_euclid(A, B)

3.97 s ± 145 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [6]:
def vectorized_euclid(X, Y):
    diff = X[np.newaxis] - Y[:, np.newaxis]
    return np.sqrt(np.einsum('ijk, ijk -> ji', diff, diff))

In [7]:
np.allclose(naive_euclid(A, B), vectorized_euclid(A, B))

True

In [8]:
%timeit vectorized_euclid(A, B)

22.5 ms ± 70.1 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [9]:
from sklearn.metrics import pairwise_distances

In [10]:
np.allclose(pairwise_distances(A, B), vectorized_euclid(A, B))

True

In [11]:
%timeit pairwise_distances(A, B, metric='euclidean')

7.14 ms ± 459 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [12]:
from numba import jit

In [13]:
@jit
def numba_euclid(X, Y):
    res = np.empty((len(X), len(Y)))
    for i in range(len(X)):
        for j in range(len(Y)):
            res[i, j] = np.sqrt(np.dot(X[i] - Y[j], X[i] - Y[j]))
    return res

In [14]:
%timeit numba_euclid(A, B)

147 ms ± 2.66 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [24]:
@jit
def vectorized_euclid_numba(X, Y):
    diff = X[np.newaxis] - Y[:, np.newaxis]
    return np.sqrt(np.einsum('ijk, ijk -> ji', diff, diff))

In [25]:
%timeit vectorized_euclid_numba(A, B)

22.2 ms ± 80 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


$d_{poinc}(a, b) = \mbox{arccosh} \left(1 + 2 \frac{||a - b ||^2}{(1 - ||a||^2) (1 - ||b|| ^2 )} \right)$

In [17]:
def poinc(a, b):
    return np.arccosh(1+ 2* np.dot(a-b, a-b)/ ((1-np.dot(a,a))*(1-np.dot(b,b))))

In [18]:
def naive_poinc(X, Y):
    res = np.empty((len(X), len(Y)))
    for i in range(len(X)):
        for j in range(len(Y)):
            res[i, j] = poinc(X[i], Y[j])
    return res

In [19]:
%timeit naive_poinc(A, B)

6.23 s ± 245 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [20]:
def numpy_poinc(X, Y):
    diff = X[np.newaxis] - Y[:, np.newaxis]
    num = np.einsum('ijk, ijk -> ji', diff, diff)
    den1 = 1 - np.einsum('ij, ji->i', X, X.T)
    den2 = 1 - np.einsum('ij, ji->i', Y, Y.T)
    den = den1[:, np.newaxis] * den2[np.newaxis]
    return np.arccosh(1 + 2 * num / den)    

In [21]:
%timeit numpy_poinc(A, B)

34.7 ms ± 2.59 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [22]:
@jit(nopython=True)
def numba_poinc(X, Y):
    def poinc(a, b):
        return np.arccosh(1+ 2* np.dot(a-b, a-b)/ ((1-np.dot(a,a))*(1-np.dot(b,b))))
    res = np.empty((len(X), len(Y)))
    i = 0
    for i in range(len(X)):
        for j in range(len(Y)):
            res[i, j] = poinc(X[i], Y[j])
    return res

In [23]:
%timeit numba_poinc(A, B)

220 ms ± 7.53 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


# Strides

# Windowed average

In [2]:
speed = np.random.rand(300000) * 75

In [3]:
def windowed_average(a, n):
    av = np.empty(len(a) - n + 1)
    for i in range(len(a) - n):
        av[i] = a[i:i+n].sum() / n
    return av

In [4]:
windowed_average(np.arange(30), 5)

array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
       15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,  0.])

In [5]:
%timeit windowed_average(speed, 5)

744 ms ± 89.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [8]:
%timeit windowed_average_conv(speed, 5)

544 µs ± 64.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [11]:
%timeit windowed_average_cumsum(speed, 5)

3.17 ms ± 509 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [6]:
def windowed_average_conv(a, n):
    return np.convolve(a, np.ones((n,))/n, mode='valid')

In [7]:
windowed_average_conv(np.arange(30), 5)

array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
       15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26., 27.])

In [9]:
def windowed_average_cumsum(a, n):
    cumsum = np.cumsum(np.insert(a, 0, 0)) 
    return (cumsum[n:] - cumsum[:-n]) / float(n)

In [10]:
windowed_average_cumsum(np.arange(30), 5)

array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
       15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26., 27.])

In [21]:
from numpy.lib.stride_tricks import as_strided

def windowed_median_strides(a, n):
    stride = a.strides[0]
    return np.median(as_strided(a, shape=[len(a) - n + 1, n], strides=[stride, stride]), axis=1)

In [22]:
windowed_median_strides(np.arange(30), 5)

array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
       15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26., 27.])

In [124]:
%timeit windowed_median_strides(speed, 5)

20.1 ms ± 220 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [3]:
from numba import guvectorize, float64, int64

In [9]:
@guvectorize(['void(float64[:], int64, float64[:])'], '(n),()->(n)', nopython=True)
def windowed_median(a, n, out):
    for i in range(len(a) - n + 1):
        out[i] = np.median(a[i: i + n])

In [10]:
windowed_median(np.arange(30), 5)

array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
       15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26., 27.,
        0.,  0.,  0.,  0.])

In [11]:
%timeit windowed_median(speed, 5)

47.4 ms ± 44.7 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [7]:
@guvectorize(['void(float64[:], int64, float64[:])'], '(n),()->(n)', nopython=True)
def windowed_average_numba(a, window_width, out):
    asum = 0.0
    count = 0
    for i in range(window_width):
        asum += a[i]
        count += 1
        out[i] = asum / count
    for i in range(window_width, len(a)):
        asum += a[i] - a[i - window_width]
        out[i] = asum / count

In [8]:
windowed_average_numba(np.arange(30), 5)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  3. ,  4. ,  5. ,  6. ,  7. ,  8. ,
        9. , 10. , 11. , 12. , 13. , 14. , 15. , 16. , 17. , 18. , 19. ,
       20. , 21. , 22. , 23. , 24. , 25. , 26. , 27. ])

In [6]:
%timeit windowed_average_numba(speed, 5)

421 µs ± 5.76 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


## Dask